# Site settings
title: Autolab Project Blog
email: autolab-dev@<span class="displaynone">X</span>andrew.cmu.edu
description: > # this means to ignore newlines until "baseurl:"
  Read on for release news, feature spotlights, development insights, and
  more!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://autolab.github.io" # the base hostname & protocol for your site
twitter_username:
github_username: autolab

exclude:
  - README.md
  - LICENSE
  - Gemfile.lock
  - Gemfile

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

sass:
  sass_dir: _sass
  style: compressed

# --- Custom metadata ---
author: Autolab Dev Team

# One of two ways to get links in the header
# (the other is to create a Jekyll page, like contributors.md)
links:
  - url: http://www.autolabproject.com/
    title: About
  - url: https://github.com/autolab/Autolab
    title: GitHub
