# Site settings
title: Autolab Project Blog
email: autolab-dev@andrew.cmu.edu
description: > # this means to ignore newlines until "baseurl:"
  Read on for releases news, feature spotlights, development insights, and
  more!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://autolab.github.io" # the base hostname & protocol for your site
twitter_username:
github_username: autolab

exclude:
  - README.md
  - LICENSE
  - Gemfile.lock
  - Gemfile

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

sass:
  sass_dir: _sass
  #style: compressed
